// src/components/ThemeSwitcher.svelte
<script>
  import { getTheme } from "src/scripts/theme";
  import { onMount } from "svelte";
  import { Moon, Sun } from "lucide-svelte";

  let theme = undefined;

  function toggleTheme() {
    if (theme === "dark") {
      theme = "light";
    } else {
      theme = "dark";
    }
  }

  $: {
    if (theme === "dark") {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
    localStorage.setItem("theme", theme);
  }

  onMount(() => {
    theme = getTheme();
  });
</script>

<button on:click={toggleTheme} class={`dark:text-white`}>
  {#if theme === "dark"}
    <Sun />
  {:else if theme === "light"}
    <Moon />
  {/if}
</button>

// src/components/ThemeSwitcher.tsx
import { useEffect, useState } from "react";
import { getTheme } from "../scripts/theme";

export default function ThemeSwitcher() {
  const [theme, setTheme] = useState(getTheme());

  const toggleTheme = () => {
    setTheme(theme === "light" ? "dark" : "light");
  };

  useEffect(() => {
    if (theme === "dark") {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
    localStorage.setItem("theme", theme);
  }, [theme]);

  return (
    <>
      <button onClick={toggleTheme} className={`dark:text-white`}>{theme === "light" ? "[Dark]" : "[Light]"}</button>
    </>
  );
}
